### Vars
@url = http://localhost:8999
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJBRE1JTiIsImV4cCI6MTcyNjE1MDMwMywiaWF0IjoxNzI2MTQ2NzAzLCJpc3MiOiJnby1hcGktZ2F0ZXdheSIsInN1YiI6ImZvb2JhciJ9.xpv4_9yL1ecucKUg3frMwFqG-GqVZwLUTiyZjcZ9IHc



### Request token
POST {{url}}/api/v1/auth/token
Content-Type: application/json

{
    "username": "foobar",
    "password": "barfoo"
}

### Invalidates the jwt token
POST {{url}}/api/v1/auth/invalidate
Content-Type: application/json
Authorization: Bearer {{token}}



### Forward - Get Tasks
GET {{url}}/api/v1/tasks?size=90000&sort=name
Authorization: Bearer {{token}}



### Forward - Save Tasks, by using: https://github.com/watanabe9090/java-api-tasks
POST {{url}}/api/v1/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "A simple task",
    "content": "Lorem Ipusum"
}

### Forward - Update Tasks, by using: https://github.com/watanabe9090/java-api-tasks
PUT {{url}}/api/v1/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": 1,
    "name": "Not just a simple task",
    "content": "Ipusum Lorem"
}


### Forward - Delete Tasks, by using: https://github.com/watanabe9090/java-api-tasks
DELETE  {{url}}/api/v1/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": 4
}


### Forward - Random route, should return 404
GET  {{url}}/another-route
Authorization: Bearer {{token}}
