volumes:
  grafana-storage: {}
services:

  go-api-gateway:
    build: .
    container_name: go-api-gateway
    ports:
      - 8999:8999
    depends_on:
      - postgres
      
  postgres:
    image: postgres
    container_name: devops-lab-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: cerberus

  prometheus:
    image: prom/prometheus:latest
    container_name: devops-lab-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    # depends_on:
    #   - go-api-gateway
    user: root
    depends_on:
      - go-api-gateway

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  # prometheus:
  #   image: prom/prometheus
  #   container_name: devops-lab-prometheus
  #   ports:
  #     - 9090:9090
  # grafana:
  #   image: grafana
  #   container_name: devops-lab-grafana
  # jenkins:
  #   image: jenkins
