services:

  go-api-gateway:
    build: .
    ports:
      - 8999:8999
    depends_on:
      - postgres
      
  postgres:
    image: postgres
    container_name: devops-lab-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: cerberus


  # prometheus:
  #   image: prom/prometheus
  #   container_name: devops-lab-prometheus
  #   ports:
  #     - 9090:9090
  # grafana:
  #   image: grafana
  #   container_name: devops-lab-grafana
  # jenkins:
  #   image: jenkins
