global:
  scrape_interval: 5s
scrape_configs:
- job_name: go-api-gateway
  scrape_interval: 2s
  scrape_timeout: 2s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - go-api-gateway:8999
